### ISSUE TITLE
Support request for broken inter-pod communication with K3s and Debian 11

### ISSUE THREAD

**Issue by Vacant0mens** [openfaas/faas-netes#997] opened 2022-08-10 20:08 UTC
I installed OpenFaaS using `arkade` (as well as `helm`) on a brand new 3-node k3s cluster, and let the deployments sit for a really long time (days, in fact). The Gateway container in the Gateway pod and the QueueWorker pod are both stuck in CrashLoopBackoff, and their logs say `can't connect to nats://nats.openfaas.svc.cluster.local:4222: nats: no servers available for connection` 

I've looked into DNS resolutions and TCP connections (using `nc`, `nslookup`, and `curl` from a test pod) , and they are working properly.

This is the same issue as [this](https://github.com/openfaas/faas-netes/issues/439) issue, but I'm not using a custom DNS within my cluster, nor am I using Rancher2, so talking to the Rancher community is moot.

## Expected Behaviour

Arkade/Helm deploys shouldn't be crashing on a fresh install.

## Current Behaviour

Gateway and QueueWorker pods won't start all the way.

## Are you a GitHub Sponsor (Yes/No?)

I am just barely beginning my journey with OpenFaaS/faas-netes. If I can get a fresh install working properly, I'll consider supporting in some way.

## List All Possible Solutions and Workarounds

I haven't found one yet.

## Steps to Reproduce (for bugs)

1. Install using `helm` or `arkade` on k3s cluster (created with Debian or Ubuntu machines)
2. gateway and queue-worker pods fail to start successfully
3. errors show up in logs

## Context

Just trying to set up a hosting environment for a home/side project.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
irrelevant, as I am currently unable to use the CLI at all.
* Docker version `docker version` (e.g. Docker 17.0.05 ):
k3s doesn't use docker.
* What version and distriubtion of Kubernetes are you using? `kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:49:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3+k3s1", GitCommit:"990ba0e88c90f8ed8b50e0ccd375937b841b176e", GitTreeState:"clean", BuildDate:"2022-07-19T01:10:03Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
```
* Operating System and version (e.g. Linux, Windows, MacOS):
Debian 11 and Ubuntu 22.04 both see this issue.

* What network driver are you using and what CIDR? i.e. Weave net / Flannel
flannel (default for k3s)

**Comment by alexellis** [comment] 2022-08-12 15:21
Hi @Vacant0mens 

We run CI on OpenFaaS on a continual basis, run it ourselves, and our customers and community run it in production.

I'm not aware of any issues or recent changes that would affect you.

So I would say this is likely down to your networking / IP ranges conflicting or something else affecting either internal DNS resolution or inter-pod network communication. 

> I've looked into DNS resolutions and TCP connections (using nc, nslookup, and curl from a test pod) , and they are working properly.

I'd suggest that you deploy nginx and try to access it from another container using a temporary curl pod.

There's also potential that there may be issues with Debian 11 and K3s itself. Are you using a Raspberry Pi?

[K3sup has a troubleshooting guide](https://github.com/alexellis/k3sup#troubleshooting) for common problems along with some notes on iptables versions in Debian vs Ubuntu.

As does [openfaas](https://docs.openfaas.com/deployment/troubleshooting/)

You may also want to check issues in [K3s with Debian](https://github.com/k3s-io/k3s/issues) and interpod communication.

I think the issue is with your setup, but happy to be wrong, and convinced that there's a problem with OpenFaaS.

If the above sounds too tricky, try out faasd on a VM on Linode or DigitalOcean? Or K3s with K3sup on another provider?

Alex

**Comment by alexellis** [comment] 2022-08-12 15:21
/set title: Support request for broken inter-pod communication with K3s and Debian 11

**Comment by Vacant0mens** [comment] 2022-08-12 18:14
I had this queued up to send before you commented, but I didn't click the button for some reason...

looks like it's an issue with DNS resolution for the cluster.
All of the settings for Gateway and QueueWorker point to `nats.openfaas.svc.cluster.local`, which gets a custom search domain appended to it, where `nats.openfaas.svc.cluster.local.` (note the `.` at the end) or `nats.openfaas.svc` do not.

Seems like you're right @alexellis that it's an issue with my setup. It looks to be an issue with my DHCP server handing out a default search domain to the nodes. Everything within the cluster resolves fine, but once it gets to the host level, it gets that search domain appended for whatever reason. Looks like all of the machines in my network are getting that search domain added when requesting DHCP, so I'll have to look into that separately. I didn't want that in my network in the first place.

I did notice that not all of the environment variables in all of the pods in the OpenFaaS helm chart use the fully qualfied domain (with `cluster.local` on the end). Specifically, I think Gateway's connection string for BasicAuthPlugin was missing the `cluster.local`. Not sure if that was on purpose or not.

Examples:
search domain gets added:
```
nslookup basic-auth-plugin.openfaas.svc.cluster.local
Server:         10.43.0.10
Address:        10.43.0.10#53

Non-authoritative answer:
Name:   basic-auth-plugin.openfaas.svc.cluster.local.mydomain.com
Address: <IP for mydomain.com>
```
resolves correctly (with the `.` at the end):
```
bash-5.1# nslookup basic-auth-plugin.openfaas.svc.cluster.local.
Server:         10.43.0.10
Address:        10.43.0.10#53

Name:   basic-auth-plugin.openfaas.svc.cluster.local
Address: 10.43.185.181
```
resolves correctly (no `.cluster.local`):
```
bash-5.1# nslookup basic-auth-plugin.openfaas.svc
Server:         10.43.0.10
Address:        10.43.0.10#53

Name:   basic-auth-plugin.openfaas.svc.cluster.local
Address: 10.43.185.181
```

**Comment by alexellis** [comment] 2022-08-13 09:13
> Seems like you're right @alexellis that it's an issue with my setup.

No worries. Good detective work on your part 👍 

> I did notice that not all of the environment variables in all of the pods in the OpenFaaS helm chart use the fully qualfied domain (with cluster.local on the end). Specifically, I think Gateway's connection string for BasicAuthPlugin was missing the cluster.local. Not sure if that was on purpose or not.

Probably not. Please feel free to send a PR if it resolves the problem for you.

Alex

**Comment by alexellis** [comment] 2022-08-25 18:40
Closing this support issue. Feel free to comment if you have any other suggestions or comments to add.

**Closed** 2022-08-25 18:39 UTC
