### ISSUE TITLE
Chart install via Rancher throws error about namespace mismatch

### ISSUE THREAD

**Issue by oskapt** [openfaas/faas-netes#383] opened 2019-03-07 11:46 UTC
I'm not sure if this is a Rancher problem, but I suspect not. Rancher is just executing `helm install`, so it looks more like a variable substitution or templating error.

When upgrading from v1 to v2 or installing v2 directly (any version), the installation throws the following error:

```
Failed to install app openfaas. Error: release openfaas failed: resource's namespace functions doesn't match the current namespace openfaas
```

I've encountered this on multiple installations, and an upgrade, so it's a reliable report and should be easy to reproduce. 

## Expected Behaviour

In v1 installations the chart installed correctly with any namespace designator for the functions namespace.

## Current Behaviour

The chart does not install.

## Possible Solution

If I install the chart without `functionNamespace` defined in `values.yaml`, it installs. I can then upgrade the chart and add `functionNamespace`, and the upgrade completes successfully.

## Steps to Reproduce (for bugs)

1. Add openfaas helm repo to Rancher catalogs
2. Deploy openfaas via Catalog Apps
3. Select catalog app (in Deploying/Installing state)
4. Error appears at top of screen
5. Edit app (Upgrade)
6. Remove `functionNamespace`
7. Save and exit
8. Chart installs
9. Edit app (upgrade)
10. Add `functionNamespace` to values
11. Chart upgrades
12. Deploy functions
13. Functions go into correct namespace

**Comment by alexellis** [comment] 2019-03-07 11:49
We do not test or provide support for faas-netes on Rancher 2.0 within the project, however there may be some people in the community who can help you.

@padiazg 

@kenfdev 

@ibuildthecloud

I'll close this issue, but feel free to keep commenting. Good luck.

Alex

**Closed by alexellis** 2019-03-07 11:49 UTC

**Comment by oskapt** [comment] 2019-03-07 12:17
I work for Rancher, and I'm pretty sure this isn't a Rancher issue. Maybe I'm wrong about that. Nothing changed in Rancher between v1 of your chart (which still works) and v2. That implies that the source of the issue is in the chart.

I raised the issue solely to let you know there's a problem, not to ask you for support. 

At least the workaround is now documented for others to find, which will keep OpenFaaS as a viable serverless solution for the Rancher community.

Thanks for your time.

**Comment by stefanprodan** [comment] 2019-03-07 12:38
This is more of a Helm problem since Helm wasn't designed to target more than one namespace. Hopefully Helm v3 will make things better.

**Comment by alexellis** [comment] 2019-03-07 13:25
I'm absolutely certain that the chart is working as designed. It's tested very frequently. Are you following the instructions from the Chart? https://github.com/openfaas/faas-netes/blob/master/chart/openfaas/README.md

That said I don't know Rancher 2.0. If absolutely necessary you can use the same namespace for the core components and the functions. We prefer to keep them separate.

What can you see that is different between the two versions of the chart seen from the Rancher catalogue?

I'd be keen to see OpenFaaS working through Rancher 2.0. What would you suggest for fixing this mismatch?

Alex

**Comment by ibuildthecloud** [comment] 2019-03-07 18:14
This is most likely an issue with Rancher I'm guessing.  Rancher will always install a helm chart into a specific namespace, passing `--namespace foo`.  So the manifests namespace and the command line arguments for namespace must match.
