### ISSUE TITLE
Install openFaas on openshift

### ISSUE THREAD

**Issue by vodasan** [openfaas/faas-netes#223] opened 2018-06-21 08:00 UTC
I try to install openFaas on my openshift instance. 

I follow this:
- https://blog.getupcloud.com/openfaas-openshift-c76658949365.
- https://blog.openshift.com/openfaas-on-openshift/

But when I invoke a function, i have an Internal Server Error. Can't reach service: XXXX

## Expected Behaviour
When I invoke function, I will have the reponse and a 200 HTTP code.

## Current Behaviour
I have an Internal Server Error with this message "Can't reach service: figlet"
However, i see a deployment in openfass-fn.

## Steps to Reproduce (for bugs)
1. Create two openShift project "openfaas", "openfass-fn"
2. Create faas-controller and add policy between the two project.
3. Apply yml files (alertmanager, ....)
4. Expose route
5. Go on the gateway, deploy figlet function
6. Invoke figlet function.

## Context
I use an instance of openshift.

## Your Environment

oc v3.9.27
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth

Server https://master.xxxxx:443
openshift v3.7.23
kubernetes v1.7.6+a08f5eeb62

**Comment by alexellis** [comment] 2018-06-21 08:08
I would have though the figlet function is running as root. which OpenShift will not allow to execute.

Maybe you could check the logs of the gateway and faas-netes to see if there was an error at deployment time of figlet? Are you certain that in the UI the Invoke button is showing as enabled and that you're using all the latest components of OpenFaaS and not an old fork from Michael's blog post? i.e. don't use https://github.com/mhausenblas/faas-netes.git

Alternatively, create a new function in Python which uses a non-root user then build it, push it to a registry or the Docker Hub and deploy that instead.

**Comment by vodasan** [comment] 2018-06-21 08:58
OK. I removed all and I use https://github.com/openfaas/faas-netes.git

Prometheus failed. In logs, i see this 

> err="Opening storage failed mkdir data/: permission denied"

![openfass-prometheus](https://user-images.githubusercontent.com/30429204/41708858-09c20da8-7542-11e8-8a4a-c7c5dc10533c.PNG)

**Comment by alexellis** [comment] 2018-06-21 09:00
I believe for Prometheus you will need to add an empty_dir - this isn't a fatal error though and you should still be able to deploy a function.

How can I set up OpenShift on Linux? I tried minishift on a Linux VM but got an error saying KVM was not supported.

**Comment by vodasan** [comment] 2018-06-21 09:07
The prometheus pod crashed but I can deploy a function. I try nodeinfo. I have a gateway time-out.

I don't know how set up OpenShift on Linux. It was done by another.

**Comment by simonpasquier** [comment] 2018-06-21 09:12
_sorry for highjacking the thread_

> I tried minishift on a Linux VM but got an error saying KVM was not supported.

It should be supported if you follow https://docs.openshift.org/latest/minishift/getting-started/setting-up-virtualization-environment.html#setting-up-kvm-driver

Otherwise [`oc cluster up`](https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md) works reasonably well for me on Linux.

**Comment by alexellis** [comment] 2018-06-21 09:35
@simonpasquier I followed all those instructions but it looks like the provider of the VM (Civo) - doesn't support nested VMs.

@vodasan - it looks like NodeInfo is working correctly from the logs?

You need to set up an empty_dir volume mount for Prometheus.

**Comment by vodasan** [comment] 2018-06-21 09:42
I have nothing in nodeinfo pod logs.

How set up an empty_dir volume mount?

**Comment by simonpasquier** [comment] 2018-06-21 09:43
FWIW I've done a quick test to deploy OpenFaaS on my local OpenShift cluster and it's working fine albeit the Prometheus crash that can be fixed by adding an emptyDir volume to the Prometheus deployment.

@vodasan are you sure that all pods are created? I had to wait for the images to be pulled otherwise I also encountered the gateway time-out.

@alexellis then I would definitely recommend `oc cluster up`. Happy to help you on this!

**Comment by simonpasquier** [comment] 2018-06-21 09:47
@vodasan I've edited the prometheus deployment from the OpenShift console to add the following bits (open the prometheus deployment page and click the "Edit YAML" button in the right-corner menu):

```yaml
        - command:
            - prometheus
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
          # <snip>
          volumeMounts:
            - mountPath: /prometheus
              name: prometheus-data
          # <snip>
      volumes:
        - emptyDir: {}
          name: prometheus-data
```

**Comment by vodasan** [comment] 2018-06-21 09:56
I update my YAML like this

```
volumes:
        - emptyDir: {}
          name: prometheus-data
        - name: prometheus-config
          configMap:
          ....
```

But pod still crash

**Comment by alexellis** [comment] 2018-06-21 10:10
You may need to make it writeable too.. 

```
          volumeMounts:
            - mountPath: /prometheus
              name: prometheus-data
              readOnly: false
```

**Comment by alexellis** [comment] 2018-06-21 10:10
Also worth looking at what we did to fix Prometheus for OpenShift in Michael's fork.

**Comment by vodasan** [comment] 2018-06-21 11:31
When I invoke nodeinfo function, I have Bad gateway or Gateway Time-out.

**Comment by alexellis** [comment] 2018-06-21 12:13
Ok so what is the name of your namespace for the functions? If it isn't openfaas-fn then you will have to update the domain suffix in the gateway-dep yaml file

**Comment by alexellis** [comment] 2018-06-21 12:15
You can also try setting direct_functions to false.

**Comment by vodasan** [comment] 2018-06-21 13:06
My second project is "openfaas-fn".
![openshift-openfass-fn](https://user-images.githubusercontent.com/30429204/41720849-9824dd6a-7564-11e8-93b0-a128f47eac96.PNG)

**Comment by alexellis** [comment] 2018-06-21 13:12
On OpenShift is traffic allowed between projects? How about the suffix in gateway and faas-netesd? Do they work on OpenShift or do you need to try something else?

**Comment by simonpasquier** [comment] 2018-06-21 13:13
@vodasan I may have a clue. How many nodes do you have in your cluster? Do you which SDN plug-in you're using? If it's the ovs-multitenant plug-in then communication between namespaces/projects is forbidden by default.

**Comment by simonpasquier** [comment] 2018-06-21 13:13
You can refer [here](https://docs.openshift.com/enterprise/3.1/admin_guide/pod_network.html#joining-project-networks) to allow communications between your projects.

**Comment by vodasan** [comment] 2018-06-21 13:20
How can i get the SDN? I try the following command but I have not the permissions.

> oc get netnamespace

**Comment by simonpasquier** [comment] 2018-06-21 13:36
Hmm, I'm afraid you'll have to ask the person that has installed the cluster. Otherwise you may try this

```
oc adm pod-network join-projects --to=openfaas-fn openfaas
```

**Comment by alexellis** [comment] 2018-06-21 13:46
Simon great to have your input. I've installed minikube and I'll see if I can get it working there with the current configuration. What I think we need is a docs page describing all the steps for OpenShift and MiniShift in the docs repo.

**Comment by vodasan** [comment] 2018-06-21 14:00
My cluster is limited. I can't do

`oc adm pod-network join-projects --to=openfaas-fn openfaas`

It's not possible to do the same but with only one project?

**Comment by alexellis** [comment] 2018-07-26 10:21
Yes it's possible, you can use the same namespace (project)

Can you use helm with OpenShift? Perhaps you can use our helm chart and configure the namespaces? If not then use "helm template" to set up everything in the same namespace and then just `kubectl apply -f`

Let me know how that goes.

**Comment by renpic** [comment] 2019-01-29 21:42
> Hmm, I'm afraid you'll have to ask the person that has installed the cluster. Otherwise you may try this
> 
> ```
> oc adm pod-network join-projects --to=openfaas-fn openfaas
> ```

I have a single node openshift, deployed with the ``ovs-multitenant`` SDN plug-in, and this command solved the network connectivity issues for me.

Without it, the two projects cannot comunicate, and that's expected, as they are isolated by design. I was looking for some way to allow the connections in the web GUI, but it seems it is necessary to use the cli command instead.

Thanks a lot!

**Comment by alexellis** [comment] 2019-02-03 21:57
You can install the functions into the same namespace (read: "project") if you want when using helm to install or generate templates.

Closing now due to inactivity.

**Comment by alexellis** [comment] 2019-02-03 21:57
Derek lock

**Closed by alexellis** 2019-02-03 21:57 UTC
