### ISSUE TITLE
Gateway is having latent communication to the faas-netes container

### ISSUE THREAD

**Issue by andelhie** [openfaas/faas-netes#333] opened 2018-12-12 21:29 UTC
## Expected Behaviour

Ran in to a bug with the Gateway Pod.  When it is running at first deployed i see it having some very latent connections times to the faas-netes container.  

## Current Behaviour

I saw this with trying to log in to the cli.

```
WARNING! Using --password is insecure, consider using: cat ~/faas_pass.txt | faas-cli login -u user --password-stdin
Calling the OpenFaaS server to validate the credentials...
WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.
credentials saved for admin http://openfaas.mydomain.com:8080
```

In the logs I saw this.

```
2018/12/12 19:15:30 Forwarded [GET] to /system/functions - [200] - 51.925134 seconds
```

## Possible Solution

Not sure this is a true solution but what worked for me was to add an env value to the gateway container of `write_debug: true`.

It then worked just fine with good numbers.

## Steps to Reproduce (for bugs)

1. Install K8s 1.12.2 with Kubespray 2.8 and checked out 2.8 tag
2.install latest helm
3.install openFaaS with helm

## Context

I cloud not log in to the CLI but the UI worked but loaded very slowly.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
version: 0.8.1
* Docker version `docker version` (e.g. Docker 17.0.05 ):
Version:           18.06.1-ce
* What version and distriubtion of Kubernetes are you using? `kubectl version`
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
* Operating System and version (e.g. Linux, Windows, MacOS):
CentOS Linux release 7.6.1810 (Core)
* Link to your project or a code example to reproduce issue:

* What network driver are you using and what CIDR? i.e. Weave net / Flannel
Calico 10.233.0.0/18

**Comment by ivanayov** [comment] 2018-12-13 08:58
Hi @andelhie,

What was the CPU usage when this happened? How many RAM do you have?
To me it seems like a problem with the VM, but if there's something that needs optimisation, we'd like to sort it out.
Can you reproduce the same with `openfaas-operator`?

Thanks,
Ivana

cc @stefanprodan

**Comment by stefanprodan** [comment] 2018-12-13 09:34
The latency could be due to Kubernetes API rate limiter, the latest openfaas-operator release has a fix for this. Please give it a try.

**Comment by alexellis** [comment] 2018-12-13 14:35
I'm not sure that would happen on an empty install.. this is on AWS though which uses CPU credits. Perhaps the instance type is too small?

**Comment by andelhie** [comment] 2018-12-13 16:23
I should have noted but this is all deployed on top of OpenStack Newton in our private cloud.

The instance are 2x4 and they are not running slow at all.

You have to remember that only thing that change is the `write_debug` was enabled on the gateway.

```
        - name: write_debug
          value: "true"
```

**Comment by andelhie** [comment] 2018-12-13 18:34
So I have a second cluster on same OpenStack infra but the K8s release is 1.11.3 and it works just fine.  If not even faster then the other one.

I will test upgrading this cluster to 1.12.2 and see if I see the same problem.

**Comment by ivanayov** [comment] 2018-12-13 18:41
That's interesting. I researched the code and did not find any possible relation between the flag and the latency. Is it possible that the time spent for printing in logs reduces the number of API calls in a short period of time?

Do you have data/logs from the networking?

Do you reproduce with `openfaas-operator`, or only with `faas-netes`?

**Comment by andelhie** [comment] 2018-12-14 16:32
I will test that next.  I did deploy this on top of Kubernetes 1.11.3 and it ran much faster.  I am now upgrading this test cluster to the same release of Kubernetes as the one that is slow.

If it slow then we know why.  If not then I will test the operator version.

**Comment by andelhie** [comment] 2018-12-19 16:53
So to update you all I am moving to 1.11.3 to the cluster as well I blow away one of the masters on my private cloud.  I hope to have it backup today to validate if there is a K8s version problem.

**Comment by alexellis** [comment] 2018-12-20 21:06
There is no `write_debug` flag for neither the gateway nor faas-netes. It sounds like a red-herring or environmental issue at this stage.

If you can reproduce the issue somehow then we can look into it. 

Alex

**Comment by alexellis** [comment] 2019-01-04 15:55
Let's close the issue but keep tracking it and commenting if you do find a way to reproduce the issue.

Alex

**Closed by alexellis** 2019-01-04 15:55 UTC

**Comment by andelhie** [comment] 2019-01-24 16:08
FYI a rebuild of my cluster to 1.12.3 fixed all the problem and it is all working great now.

**Comment by alexellis** [comment] 2019-01-24 20:02
Thank you for updating us 👍
