### ISSUE TITLE
deployment to namespaces not working

### ISSUE THREAD

**Issue by albertkohl-monotek** [openfaas/faas-netes#789] opened 2021-05-03 19:33 UTC
I tried setting up custom namespace dev-fn as per: [docs](https://docs.openfaas.com/reference/namespaces/)
i know it shows that it's alpha, and i'm using the code from the master branch, so maybe that's why its not working, but if i run faas-cli namespaces, i show only the default namespace.

## Expected Behaviour
faas-cli namespaces
Namespaces:
 - openfaas-fn
 - dev-fn

## Current Behaviour
faas-cli namespaces
Namespaces:
 - openfaas-fn

## Are you a GitHub Sponsor (Yes/No?)
Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [X] No

## List All Possible Solutions and Workarounds
not sure if this feature is available in current master branch considering docs notates that it's an Alpha feature. also, could be user error. my yml files are attached.

## Steps to Reproduce (for bugs)
kubectl apply -f  [file]
[dev-fn-namespace.txt](https://github.com/openfaas/faas-netes/files/6417210/dev-fn-namespace.txt)

## Context
i'd like to deploy functions to different namespaces such as prod/dev/staging 

## Your Environment
K8s on bare-metal
* FaaS-CLI version ( Full output from: `faas-cli version` ):
0.13.1

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* What version and distriubtion of Kubernetes are you using? `kubectl version`
1.21 (i believe)
* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

* What network driver are you using and what CIDR? i.e. Weave net / Flannel
Flannel

also worth a note, if i deploy the function to that namespace, it works fine. but i cant invoke, nor see it in the gateway website.

**Comment by alexellis** [comment] 2021-05-04 18:02
Hi @albertkohl-monotek this works for me and I tried it last week.

You need to share your command that you used to install openfaas for us to help and see if you've missed something.

I'll close this issue, since I can't reproduce any problem here, but feel free to keep commenting.

Alex

**Closed by alexellis** 2021-05-04 18:02 UTC

**Comment by albertkohl-monotek** [comment] 2021-05-04 18:14
thanks Alex, i installed using git and kube apply. for some reason in the past when i used the arkade it would throw errors.

```
#clone the git repo:
git clone https://github.com/openfaas/faas-netes
cd faas-netes

#set a random password for gateway
PASSWORD=$(head -c 12 /dev/urandom | shasum| cut -d' ' -f1)
echo $PASSWORD>pw
#password for openfaas gateway can be found in pw file

#deploy openfaas
kubectl apply -f ./namespaces.yml
kubectl create configmap openfaas-ca-root-key \
    --from-file=/home/albertkohl/certs/rootCA.pem \
    -n openfaas

kubectl -n openfaas create secret generic basic-auth \
--from-literal=basic-auth-user=admin \
--from-literal=basic-auth-password="$PASSWORD"
kubectl apply -f ./yaml

```

**Comment by alexellis** [comment] 2021-05-04 18:28
Thank you for providing that, it really helps. You've missed out the additional permissions for the ClusterRole.

You can't simply apply the `yaml` folder and hope that it would work.

Please see the docs here. You can use arkade, or modify the helm install command that we provide.

https://docs.openfaas.com/reference/namespaces/

Alex

**Comment by albertkohl-monotek** [comment] 2021-05-04 18:33
let me clarify, i also added this yml file (added it in my original post) 
[dev-fn-namespace.txt](https://github.com/openfaas/faas-netes/files/6423245/dev-fn-namespace.txt)

i THOUGHT i was doing that with that. am i mistaken? (probably am, i'm still learning k8s)

**Comment by alexellis** [comment] 2021-05-04 18:48
Can you please follow the docs instead of doing it your own way?

`kubectl apply -f ./yaml` - this is not an appropriate installation method because you need to customise the roles to support a Cluster role. See the helm readme if you prefer to use helm over arkade

**Comment by albertkohl-monotek** [comment] 2021-05-04 18:51
okay, i'll nuke my cluster and try arkade again. if it fails to install like it had in the past, would you mind if i repost here? or should i start a new thread?

**Comment by alexellis** [comment] 2021-05-04 18:57
Please don't open another issue for this discussion. The docs work as expected, I just tried them, if you follow them line by line.

**Comment by albertkohl-monotek** [comment] 2021-05-13 15:27
Alex, i finally got around to re-deploying openfaas into a fresh k8's cluster using arkade, it worked great! i think when i was first messing with it i was using microk8s and had some issues, and found a writeup somewhere that talked about applying the .yml files, sorry for the confusion on that. i also got the name spaces to work properly per your documentation, and that's working as well, so thanks!

quick question though, that i didnt see in the docs. Is there a way for me to dynamically set variables in python scripts based off the namespace? 

for example, i in the stack.yml i can do something like:

`namespace: ${namespace:-openfaas-dev}`

how can i do the same inside the python script?
for example, something like:
```
mystring = "hello, you are running this in the " + ${namespace:-openfaas-dev} + " namespace"
print(mystring)
```
