### ISSUE TITLE
minikube: getsockopt: connection refused

### ISSUE THREAD

**Issue by sxhysj** [openfaas/faas-netes#165] opened 2018-03-21 15:23 UTC
I use Mac OS X 10.13, minikube and faas-netes and followed the guide https://medium.com/devopslinks/getting-started-with-openfaas-on-minikube-634502c7acdf. However, Some error message pops up:
```
Put http://192.168.25.136:31112/system/functions: dial tcp 192.168.25.136:31112: getsockopt: connection refused
```

## Expected Behaviour

For command:
```
faas-cli deploy -f hello-python.yml --gateway $gw 
```
The expected behaviour should be:
```
Deploying: hello.
No existing function to remove
Deployed.
URL: http://192.168.99.100:31112/function/hello-python
```

## Current Behaviour

The following output is popped up:
```
Deploying: hello-python.

Is FaaS deployed? Do you need to specify the --gateway flag?
Put http://192.168.25.136:31112/system/functions: dial tcp 192.168.25.136:31112: getsockopt: connection refused
```

## Steps to Reproduce (for bugs)

1. kube-system create sa tiller \
 && kubectl create clusterrolebinding tiller \
 --clusterrole cluster-admin \
 --serviceaccount=kube-system:tiller
2. helm init --skip-refresh --upgrade --service-account tiller
3. https://github.com/openfaas/faas-netes && cd faas-netes
4. helm upgrade --install --debug --reset-values --set async=false --set rbac=false openfaas openfaas/
5. faas-cli new --lang python hello-python
6. faas-cli build -f ./hello-python.yml
7. export gw=http://$(minikube ip):31112
8. faas-cli deploy -f hello-python.yml --gateway $gw

## Context

I completely follow the guide https://medium.com/devopslinks/getting-started-with-openfaas-on-minikube-634502c7acdf

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
17.12.0-ce

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Minikube, faas-netes

* Operating System and version (e.g. Linux, Windows, MacOS):
Mac OS 10.13.3

* Link to your project or a code example to reproduce issue:

**Comment by ericstoekl** [comment] 2018-03-21 22:53
Derek add label: question

**Comment by ericstoekl** [comment] 2018-03-21 22:53
Did you push your image to Docker Hub before attempting to use it in your minikube cluster?

**Comment by vosmith** [comment] 2018-03-22 01:11
@sxhysj somewhere between step 6 and step 8, you need to `faas-cli push -f ./hello-python.yml`

**Comment by sxhysj** [comment] 2018-03-22 05:16
@ericstoekl @vosmith Thanks. Now i am able to deploy the function. But cannot invoke the function
```
echo -n "test" | faas-cli invoke hello-python --gateway $gw
```

In the command line it returns:
```
Post http://192.168.25.136:31112/function/hello-python: EOF
Cannot connect to OpenFaaS on URL: http://192.168.25.136:31112
```

If I use the 31112 UI, it returns:
![2018-03-22 1 14 11](https://user-images.githubusercontent.com/28251436/37752431-1dcbd402-2dd3-11e8-894b-8d2e406f4e19.png)

In the K8s dashboard, namespace openfaas-fn, the service is alive.
![2018-03-22 1 15 04](https://user-images.githubusercontent.com/28251436/37752443-27e65494-2dd3-11e8-9068-32f4b10c2ae7.png)

**Comment by alexellis** [comment] 2018-03-22 11:00
We're trying to reproduce the issue but it looks like an issue with your minikube setup rather than something with OpenFaaS specifically.

Can you do some more diagnostics and put it into pastern or a Gist for us?

```
kubectl get all -n openfaas
kubectl get all -n openfaas-fn
kubectl get all -n kube-system
```

**Comment by sxhysj** [comment] 2018-03-22 13:12
For command
```
kubectl get all -n openfaas
```
![2018-03-22 9 10 58](https://user-images.githubusercontent.com/28251436/37772431-9222fe1a-2e15-11e8-987a-08ef19c849a7.png)

For command
```
kubectl get all -n openfaas-fn
```
![2018-03-22 9 11 41](https://user-images.githubusercontent.com/28251436/37772449-a3668c96-2e15-11e8-8c4f-ce6df3f6c8f7.png)

For command
```
kubectl get all -n kube-system
```
![2018-03-22 9 12 11](https://user-images.githubusercontent.com/28251436/37772484-b97f1854-2e15-11e8-82d7-2e6178ea22c6.png)

**Comment by alexellis** [comment] 2018-03-22 14:07
It looks like you may have installed with helm - that's OK but I'm not sure why you've set up ingress to use LoadBalancer? It should be using "NodePort" which I think is the default option.

I may be wrong but I think that minikube doesn't have the ability to provide a LoadBalancer.

You may also want to use the kubeadm provisioner which is listed there in the docs.. so I'd suggest blowing away that minikube instance and starting over.

**Comment by BurtonR** [comment] 2018-05-19 13:27
I'm going to close this issue as it appears to be a fault of the minikube deployment since minikube does not support the `LoadBalancer`. 
@sxhysj  feel free to continue to comment if you are still having issues even after updating to use `NodePort`

**Comment by BurtonR** [comment] 2018-05-19 13:27
Derek close

**Closed by BurtonR** 2018-05-19 13:27 UTC
Labels: question
