### ISSUE TITLE
Multiple namespace for openfaas within same kubernetes cluster

### ISSUE THREAD

**Issue by rakeshbshukla** [openfaas/faas-netes#263] opened 2018-07-23 15:21 UTC
I am trying to run multiple namespace of openfaas within same kubernetes cluster but i am not able to install using helm

When i try to run with different namespace i am getting the below error
Error: release openfass-2 failed: clusterroles.rbac.authorization.k8s.io "faas-controller" already exists 

Is it possible to run openfaas with different namespace within same cluster and how can i achieve that?

**Comment by alexellis** [comment] 2018-07-23 19:50
Duplicate of https://github.com/openfaas/faas-netes/issues/211

We believe that changing the ClusterRole to Role will resolve the issue. Work was started on this in one of the open PRs.

**Comment by alexellis** [comment] 2018-07-23 19:51
Derek add label: duplicate

**Comment by alexellis** [comment] 2018-07-24 08:49
We are working on this right now with @stefanprodan putting together the PR.

**Closed** 2018-07-25 11:38 UTC
Labels: duplicate

**Comment by alexellis** [comment] 2018-07-26 08:49
Perhaps you could also apply NetworkPolicy for further isolation? Example in https://github.com/stefanprodan/openfaas-flux

Are you running multiple tennants or dev/staging/prod in the same cluster?
