### ISSUE TITLE
Issues found with Istio 1.1.7 on GKE

### ISSUE THREAD

**Issue by lomeshpatel** [openfaas/faas-netes#473] opened 2019-07-08 18:57 UTC
The issue is exactly the same as described in #369

## Expected Behaviour

OpenFaaS should work with Istio v1.1.7 or newer on GKE.

## Current Behaviour

OpenFaaS gateway, faas-idler and queue-worker are crashing at startup:
```
NAME                                 READY   STATUS             RESTARTS   AGE
alertmanager-6db9584ccf-sz25j        1/1     Running            0          80s
basic-auth-plugin-56ccf99c59-sbj88   2/2     Running            0          80s
faas-idler-78d87f976b-d4wgj          1/2     CrashLoopBackOff   3          80s
gateway-78b4cb9489-9sqt2             2/3     CrashLoopBackOff   3          80s
nats-5d7898f77d-kbnv2                1/1     Running            0          80s
prometheus-6c56475cb4-m4qpp          1/1     Running            0          80s
queue-worker-7b99b586d8-mpnz9        1/2     CrashLoopBackOff   3          80s
```

faas-idler logs:
```
panic: invalid character 'o' in literal null (expecting 'u')

goroutine 1 [running]:
main.main()
	/go/src/github.com/openfaas-incubator/faas-idler/main.go:63 +0x66d
```

gateway logs:
```
2019/07/08 18:33:15 HTTP Read Timeout: 1m5s
2019/07/08 18:33:15 HTTP Write Timeout: 1m5s
2019/07/08 18:33:15 Binding to external function provider: http://127.0.0.1:8081/
2019/07/08 18:33:15 Async enabled: Using NATS Streaming.
2019/07/08 18:33:15 Opening connection to nats://nats.openfaas.svc.cluster.local:4222
2019/07/08 18:33:15 Connect: nats://nats.openfaas.svc.cluster.local:4222
2019/07/08 18:33:15 EOF
```

queue-worker logs:
```
Loading basic authentication credentials
Connect: nats://nats.openfaas.svc.cluster.local:4222
can't connect to nats://nats.openfaas.svc.cluster.local:4222: EOF
panic: can't connect to nats://nats.openfaas.svc.cluster.local:4222: EOF

goroutine 1 [running]:
log.Panic(0xc420041df8, 0x1, 0x1)
	/usr/local/go/src/log/log.go:326 +0xc0
main.main()
	/go/src/github.com/openfaas/nats-queue-worker/main.go:220 +0x468
```

I can get the infrastructure pieces working by turning `async=false`. Here's my `helm` command:
```
helm upgrade openfaas --install openfaas/openfaas \
  --namespace openfaas \
  --set basic_auth=true \
  --set functionNamespace=openfaas-fn \
  --set operator.create=true \
  --set exposeServices=false \
  --set async=false
```

I am unable to deploy any functions even with this. They just keep crashing. Here's some logs from `nodeinfo` function pod:
```
2019/07/08 18:25:41 Version: 0.14.4	SHA: ced4ee56dc003cf4f3baa0954ab692f4be54f57b
2019/07/08 18:25:41 Read/write timeout: 5s, 5s. Port: 8080
2019/07/08 18:25:41 Writing lock-file to: /tmp/.lock
2019/07/08 18:25:41 Metrics server. Port: 8081
2019/07/08 18:25:48 SIGTERM received.. shutting down server in 5s
2019/07/08 18:25:48 Removing lock-file : /tmp/.lock
2019/07/08 18:25:53 No new connections allowed. Exiting in: 5s
```

## Steps to Reproduce (for bugs)

1. Create GKE cluster using the GCP console
2. Install Istio 1.1.7 using [Istio instructions with helm and tiller](https://istio.io/docs/setup/kubernetes/install/helm/#option-2-install-with-helm-and-tiller-via-helm-install)
3. Install OpenFaas using [these instructions](https://github.com/openfaas/faas-netes/tree/master/chart/openfaas).
Here's my `helm` command,
```
helm upgrade openfaas --install openfaas/openfaas \
  --namespace openfaas \
  --set basic_auth=true \
  --set functionNamespace=openfaas-fn \
  --set operator.create=true \
  --set exposeServices=false
```

## Context

I'm trying to do a POC to enable creating new REST endpoints backed by functions in a secure environment. These endpoints can either be used by internal services or made available publicly with authentication. All internal communication must be secured using Istio's mTLS.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
```
CLI:
 commit:  5fcdc692e4adf04977775ea78f79b3534a44fb36
 version: 0.8.21
```

* What version and distriubtion of Kubernetes are you using? `kubectl version`
```
Client Version: version.Info{
  Major:"1", 
  Minor:"13", 
  GitVersion:"v1.13.7", 
  GitCommit:"4683545293d792934a7a7e12f2cc47d20b2dd01b", 
  GitTreeState:"clean", 
  BuildDate:"2019-06-06T01:46:52Z", 
  GoVersion:"go1.11.5", 
  Compiler:"gc", 
  Platform:"linux/amd64"
}
Server Version: version.Info{
  Major:"1", 
  Minor:"13+",
  GitVersion:"v1.13.7-gke.8",
  GitCommit:"7d3d6f113e933ed1b44b78dff4baf649258415e5",
  GitTreeState:"clean",
  BuildDate:"2019-06-19T16:37:16Z",
  GoVersion:"go1.11.5b4",
  Compiler:"gc",
  Platform:"linux/amd64"
}
```

* Istio version:
```
version.BuildInfo{
  Version:"1.1.7",
  GitRevision:"eec7a74473deee98cad0a996f41a32a47dd453c2",
  User:"root",
  Host:"341b3bf0-76ac-11e9-b644-0a580a2c0404",
  GolangVersion:"go1.10.4",
  DockerHub:"docker.io/istio",
  BuildStatus:"Clean",
  GitTag:"1.1.6-6-geec7a74"
}
```

**Comment by burtonr** [comment] 2019-07-08 19:30
I am no Istio expert, but could it be that your issue is related to the different versions of what was tested and what you're using?

You mention using Istio `1.1.7` where Stefan mentions using `1.0.3`. Looking through the Istio changelogs, I found [this incompatability notice](https://istio.io/docs/setup/kubernetes/upgrade/notice/) to indicate they've removed most of the mixer CRDs.

Perhaps you could try with a previous version of Istio?

I also found this: https://github.com/knative/eventing/issues/1043 where they mention issues with NATS and Istio 1.1+.

**Comment by lomeshpatel** [comment] 2019-07-08 20:34
Thank you for the response, @burtonr.

The removal of mixer CRDs you mentioned is for between Istio version `1.1.+` and `1.2.+`. But, I could certainly try with the `1.0.+` version of Istio.

The Knative issue you posted talks about disabling Istio sidecar injection being a potential fix. [Stefan's fix](https://github.com/openfaas/faas-netes/pull/387/files) was to disable the Istio sidecar injection for NATS and AlertManager. I've confirmed that those configs are in place for my installation.

**Comment by stefanprodan** [comment] 2019-07-08 20:47
Hi @lomeshpatel 

Can you please try disabling mTLS for outbound traffic to NATS and see if it works?

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: nats
  namespace: openfaas
spec:
  host: "nats.openfaas.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: DISABLE
---
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: nats
  namespace: openfaas
spec:
  targets:
  - name: nats
    ports:
    - number: 4222
```

**Comment by lomeshpatel** [comment] 2019-07-09 13:13
That got the `queue-worker` running, but `basic-auth-plugin` is now crashing.

```
NAME                                 READY   STATUS             RESTARTS   AGE
alertmanager-75f77464c5-kzm2d        1/1     Running            0          7m32s
basic-auth-plugin-5dd4796845-grrft   1/2     CrashLoopBackOff   6          7m32s
faas-idler-78d87f976b-8ctxf          1/2     CrashLoopBackOff   6          7m32s
gateway-c6b67ccb6-sbdb6              2/3     CrashLoopBackOff   6          7m32s
nats-5d7898f77d-x66fj                1/1     Running            0          7m32s
prometheus-bd4fd85f5-smj95           1/1     Running            0          7m31s
queue-worker-7b99b586d8-wjm9b        2/2     Running            4          7m31s
```

`faas-idler` and `gateway` have the same logs. Here's logs from `basic-auth-plugin`
```
2019/07/09 13:08:14 Listening on: 8080
```

**Comment by alexellis** [comment] 2019-07-09 14:13
The `basic-auth-plugin` only listens for HTTP and doesn't make outbound calls. I can't think why Istio would cause it to crash, but @stefanprodan is the Istio expert here.

Can you provide the events from the openfaas namespace ordered by time? See the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/) for more info on that.

**Comment by alexellis** [comment] 2019-07-09 14:15
I would agree with @burtonr about the statement "The issue is exactly the same as described in x". I don't think this is accurate, given that all of the versions have changed in both projects since that date and the original issue was fixed by Stefan through config.

I don't know if Stefan has time to look at this, but if you want to suggest a fix we'll be happy to look at it.

**Comment by alexellis** [comment] 2019-07-09 14:47
The Istio support was added by @stefanprodan, who is going to be away until the end of July.

Everything in this guide was working when published and I am aware of several people who have used it since. I would be surprised if there was a complete regression in NATS, but perhaps the configuration needs to be updated to match what is expected by 1.1.7 and newer?

https://github.com/stefanprodan/istio-gke/blob/master/docs/openfaas/00-index.md

If it's urgent and you can't wait until early August, then you could try the Istio Slack for technical support.

Alex

**Comment by lomeshpatel** [comment] 2019-07-09 15:35
Thank you very much, @alexellis!

I started by following that guide, but decided to deviate from it in favor of using helm charts. I will try following the guide as is and see if that makes any difference. I will also try earlier version of Istio.

This can certainly wait. In the meantime, I'll update this post with my findings, if any.

**Comment by alexellis** [comment] 2019-07-09 19:08
One other thought for you @lomeshpatel - https://github.com/openfaas-incubator/openfaas-linkerd2

> This can certainly wait. In the meantime, I'll update this post with my findings, if any.

Your help would be appreciated 👍 

Alex

**Comment by wmorgan** [comment] 2019-07-09 20:40
Happy to help with anything Linkerd-related if you do go that route. 😁

**Comment by alexellis** [comment] 2019-08-07 20:24
@lomeshpatel please could you have another look? @stefanprodan has sent in PR #488 to fix this issue and we expect it to be all working now.

**Closed** 2019-08-07 20:23 UTC
