### ISSUE TITLE
(Unable to reproduce) kafka connector pod failed with "invalid character 'E' looking for beginning of value"

### ISSUE THREAD

**Issue by manukasa** [openfaas/faas-netes#479] opened 2019-07-23 11:21 UTC
kafka-connector-6f68cf7675-26gt7 - crashloopBackoff 
error in the Logs shows
2019/07/23 11:14:15 invalid character 'E' looking for beginning of value
## Expected Behaviour

Pod should have run with out restarts 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

docker version
Client:
 Version:           18.06.2-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        6d37f41
 Built:             Sun Feb 10 03:48:06 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.2-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       6d37f41
  Built:            Sun Feb 10 03:46:30 2019
  OS/Arch:          linux/amd64
  Experimental:     false

* What version and distriubtion of Kubernetes are you using? `kubectl version`
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
* Operating System and version (e.g. Linux, Windows, MacOS):
Linux master-1 4.15.0-54-generic #58~16.04.1-Ubuntu SMP Mon Jun 24 13:21:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project or a code example to reproduce issue:

* What network driver are you using and what CIDR? i.e. Weave net / Flannel
calico

**Comment by alexellis** [comment] 2019-07-23 21:26
Hi,

Thanks for using OpenFaaS.

Is there anything you want to tell us about your environment? Are you using something like Istio?

How did you deploy the components? I would recommend you follow the blog post and report back after that. 

@martindekov is the author of the post.

https://www.openfaas.com/blog/kafka-connector/

Please also check open issues and PRs.

Alex

**Comment by alexellis** [comment] 2019-07-23 21:29
Cc @kwojcicki who I believe has it deployed on his cluster

**Comment by manukasa** [comment] 2019-07-24 05:47
@alexellis, thanks! 
i will recheck with link provided and will get back to you

**Comment by manukasa** [comment] 2019-07-24 05:52
@kushalarya

**Comment by alexellis** [comment] 2019-07-24 08:36
Hi @manukasa @kushalarya, you both raised the same issue, so I will close one as a duplicate.

Please can you provide all the context and information required?

You should not use OpenFaaS or the connector without authentication enabled.

The blog post is the best tutorial you can follow.

Alex

**Comment by alexellis** [comment] 2019-07-24 08:36
Duplicate of https://github.com/openfaas-incubator/kafka-connector/issues/50

**Comment by alexellis** [comment] 2019-07-24 08:38
Please fill out "Steps to Reproduce (for bugs)" completely.

**Comment by kushalarya** [comment] 2019-07-24 13:29
I'm following this guide 
[https://www.openfaas.com/blog/kafka-connector/](https://www.openfaas.com/blog/kafka-connector/)
while installing Openfaas flag `basic_auth` is set to `true`

I have a new finding. In logs of kafka-connector pod
``` $ k get pods kafka-connector-6774f798c5-m97mh -v 9 ```

noticed this :
`I0724 18:50:40.390127   24419 get.go:563] no kind is registered for the type v1beta1.Table in scheme "k8s.io/kubernetes/pkg/api/legacyscheme/scheme.go:29"`

**Comment by alexellis** [comment] 2019-07-24 14:03
What Kubernetes version are you using? On what cloud or distro (k8s/openshift)? 

Are you using anything peculiar like Istio?

**Comment by alexellis** [comment] 2019-07-24 14:48
I've just walked through the whole tutorial end-to-end on DigitalOcean Kubernetes with 1.14.

I had no issues whatsoever. To help out, I think we're going to need more details from your end on what you may be doing differently.

![Screenshot 2019-07-24 at 15 48 06](https://user-images.githubusercontent.com/6358735/61803636-72d60980-ae2a-11e9-8369-0e916c69cc9d.png)

**Comment by manukasa** [comment] 2019-07-24 14:51
> What Kubernetes version are you using? On what cloud or distro (k8s/openshift)?
> we are using Kubernetes 1.13.5 , deployed the cluster using kubespray , deployed on baremetal -Ubuntu 16.0.4 
> Are you using anything peculiar like Istio?
No we didnt use Istio etc

**Comment by alexellis** [comment] 2019-07-24 15:46
You appear to be using Kubernetes 1.13, but on what cloud?

Alex

**Comment by alexellis** [comment] 2019-07-24 16:11
Please can you update your helm chart repo and install the connector again?

I've added some verbose logging which may give us more of a clue of where things may be going wrong in your setup.

**Comment by alexellis** [comment] 2019-07-24 16:12
This reminds me of a similar issue I saw with @stefanprodan and @LucasRoesler 

Can you confirm what functions you have deployed? Are you using the Operator and CRD, or faas-netes?

**Comment by martindekov** [comment] 2019-07-24 23:07
I have deployed the connector:
![image](https://user-images.githubusercontent.com/34942004/61834507-e86cc480-ae80-11e9-85f8-928635112787.png)

**Comment by martindekov** [comment] 2019-07-24 23:08
Not sure how to reproduce

**Comment by manukasa** [comment] 2019-07-25 06:04
> Please can you update your helm chart repo and install the connector again?
> 
> I've added some verbose logging which may give us more of a clue of where things may be going wrong in your setup.

Sure let us try that and will get back to you .
Thanks!

**Comment by alexellis** [comment] 2020-11-03 21:37
/lock: closing as inactive. Feel free to raise a new issue if this is still required

**Closed by alexellis** 2020-11-03 21:37 UTC
